### ISSUE TITLE
Milestone Task: Programs

### ISSUE THREAD

**Issue by IrisFleischer** [orchid-initiative/postpartum-larc#40]
Write 3-4 programs to read in, subset, flag, and aggregate the data in a way that can be passed off well to Jim's data visualization tool.

- [x] Subset/flag for LARCs
   - [x] Flag between subcutaneous (Nexplanon) vs. IUD LARC procedures. 
   > Leave Ethnicity/Race as a categorical variable and add a description
- [x] Multiple aggregations
   > Should count the total for included L&D, count the total number of LARCS, count the total number of subcutaneous and intrauterine
   > Include an overall exclusion count.
- [x] Work on memory efficiency and runtime, test the program on larger datasets (~2 million records)
   > ACCEPTANCE CRITERIA: The program should be able to run on Rhonda's Chromebook
   > Preferable if the data comes from Travis/Synthea
   > Collaborate with Riley
- [x] Submit a pull request to QA by the end of March
   > Program should be coded in a way that the process can be repurposed for different, future projects.
- [x] Pass the data on to Visualization 
   > Iterate with Jim throughout March
